# Generated by Django 4.1.4 on 2023-01-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prize', models.DecimalField(decimal_places=2, max_digits=5000)),
                ('Prize2', models.DecimalField(decimal_places=2, max_digits=15000)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Info', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Info', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Abon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('prizein', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finaltraininng.prize')),
                ('trainerin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finaltraininng.trainer')),
                ('trainin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finaltraininng.training')),
            ],
        ),
    ]
