# Generated by Django 4.1.4 on 2023-01-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltraininng', '0005_remove_abon_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='Name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
