# Generated by Django 4.1.4 on 2023-01-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltraininng', '0006_alter_trainer_name_alter_training_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='abon',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
