# Generated by Django 4.1.4 on 2023-01-21 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finaltraininng', '0008_wallet_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.PositiveBigIntegerField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user_chat_id',
        ),
        migrations.AddField(
            model_name='wallet',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finaltraininng.user'),
        ),
        migrations.AlterField(
            model_name='order',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finaltraininng.user'),
        ),
    ]
