# Generated by Django 4.1.4 on 2023-01-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finaltraininng', '0009_user_remove_wallet_user_chat_id_wallet_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
